# Generated by Django 6.0.2 on 2026-02-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
